# Generated by Django 4.2.10 on 2024-08-16 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oddam_w_dobre_rece_app', '0002_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(to='oddam_w_dobre_rece_app.category'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=16)),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('pick_up_comment', models.TextField()),
                ('categories', models.ManyToManyField(to='oddam_w_dobre_rece_app.category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oddam_w_dobre_rece_app.institution')),
                ('user', models.ForeignKey(blank=True, default=django.db.models.deletion.SET_NULL, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
